#!/bin/bash
#SBATCH --partition=edu5
#SBATCH --tasks=1
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:0
#SBATCH --nodes=1

#SBATCH --job-name=lab1_ex4
#SBATCH --output=outputs/R-%x.%j.out
#SBATCH --error=outputs/R-%x.%j.err

./bin/lab1_ex4_sol $1
